// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZFzfsmRVatFkddNGITxXIsc3rNluD7Mk',
    appId: '1:325664852023:web:711729ab2230fc7f3bd7b2',
    messagingSenderId: '325664852023',
    projectId: 'flutterrent-3124f',
    authDomain: 'flutterrent-3124f.firebaseapp.com',
    storageBucket: 'flutterrent-3124f.appspot.com',
    measurementId: 'G-18BST5RCBL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2ebPFb30nrlPSygANA1HGJf4p5MDvizw',
    appId: '1:325664852023:android:4252da254d9111db3bd7b2',
    messagingSenderId: '325664852023',
    projectId: 'flutterrent-3124f',
    storageBucket: 'flutterrent-3124f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxAPIy79lXAN6RgjukOZ-0dEdwX8GQXQo',
    appId: '1:325664852023:ios:83d2165babc9fdbb3bd7b2',
    messagingSenderId: '325664852023',
    projectId: 'flutterrent-3124f',
    storageBucket: 'flutterrent-3124f.appspot.com',
    iosBundleId: 'com.example.flutterRentApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxAPIy79lXAN6RgjukOZ-0dEdwX8GQXQo',
    appId: '1:325664852023:ios:83d2165babc9fdbb3bd7b2',
    messagingSenderId: '325664852023',
    projectId: 'flutterrent-3124f',
    storageBucket: 'flutterrent-3124f.appspot.com',
    iosBundleId: 'com.example.flutterRentApps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZFzfsmRVatFkddNGITxXIsc3rNluD7Mk',
    appId: '1:325664852023:web:5c5850317a616e8c3bd7b2',
    messagingSenderId: '325664852023',
    projectId: 'flutterrent-3124f',
    authDomain: 'flutterrent-3124f.firebaseapp.com',
    storageBucket: 'flutterrent-3124f.appspot.com',
    measurementId: 'G-P6SS40SBB3',
  );

}